[api]
api_token = "xxxxx"
email = "yyyy"
domain = "zzzzz.com"
sub_domain = "test.zzzzz.com"

[app]
update_ipv4_dns_record = true
update_ipv6_dns_record = true
enable_cloudflare_proxied = false
ttl = 1
send_ddns_custom_updated_notify =  false